language: node_js
node_js:
- '12'
services:
- mongodb
before_install:
  - pip install --user awscli
cache:
  directories:
    - node_modules
install:
   - npm install
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: no4good/aws-dep
  bucket: traviscicd
  region: us-east-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: traviscicd
  key: latest.zip
  bundle_type: zip
  application: nato
  deployment_group: nato
  region: us-east-2
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - aws configure set region us-east-2 --profile travis
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET_KEY
  - aws s3 ls
  - aws s3 ls s3://traviscicd
  - mv latest.zip dpl_cd_upload/latest.zip