version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/nato

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
    - location: create.sh
  ApplicationStart:
    - location: scripts/app-start.sh
      runas: ubuntu
